name: Pull Request Checks
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html pytest-cov

      - name: Run tests with reports
        run: |
          mkdir -p reports
          python -m pytest -v \
            --junitxml=reports/pytest-junit.xml \
            --html=reports/pytest-report.html --self-contained-html \
            --cov=. --cov-report=xml:reports/coverage.xml --cov-report=html:reports/coverage-html

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports

      # PR comment + Check with a table of ALL tests (passed/failed/skipped)
      - name: Publish full test list to PR
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: 'reports/pytest-junit.xml'
          check_name: 'Pytest Results'
          include_passed: true         # include ✅ tests in the tables
          detailed_summary: true       # full table of all tests
          comment: true                # post/maintain a PR comment
          update_check: true           # robust update for large runs
